spring.application.name=ms-nutria-mongodb
spring.data.mongodb.uri=${MONGODB_URI}
spring.security.user.name=${USER}
spring.security.user.password=${PASSWORD}
server.port=${PORT:8080}
fastapi.url=${FASTAPI_URL}
spring.data.redis.url=${REDIS_URI}